from repoglance import cache as cachemod
from repoglance.dedup import detect_duplicates
from repoglance.plugins import run_plugins
from repoglance.scanner import scan
from repoglance.vendored import is_generated_content, is_vendored_path


def test_vendored_path_and_content():
    assert is_vendored_path("node_modules/foo/bar.js")
    assert is_vendored_path("static/app.min.js")
    assert is_vendored_path("proto/thing_pb2.py")
    assert not is_vendored_path("src/app.py")
    assert is_generated_content("// Code generated by protoc. DO NOT EDIT.\nx=1\n")
    assert not is_generated_content("def real():\n    return 1\n")


def test_scan_excludes_vendored(tmp_path):
    (tmp_path / "app.py").write_text("x = 1\n", encoding="utf-8")
    (tmp_path / "lib.min.js").write_text("var a=1;\n", encoding="utf-8")
    (tmp_path / "gen.py").write_text("# @generated\ny = 2\n", encoding="utf-8")
    res = scan(tmp_path)
    paths = {f.path for f in res.files}
    assert "app.py" in paths
    assert "lib.min.js" not in paths       # vendored by suffix
    assert "gen.py" not in paths           # generated by marker
    assert res.vendored_files == 2

    res2 = scan(tmp_path, include_vendored=True)
    assert {"app.py", "lib.min.js", "gen.py"} <= {f.path for f in res2.files}


def test_duplicate_detection():
    block = "".join(f"line number {i} here does stuff\n" for i in range(8))
    contents = {"a.py": block + "unique_a = 1\n", "b.py": "header_b = 0\n" + block}
    dd = detect_duplicates(contents, window=6)
    assert dd.blocks
    assert dd.duplicated_lines > 0
    assert 0 < dd.ratio <= 1


def test_no_duplicates_on_unique():
    contents = {"a.py": "alpha = 1\nbeta = 2\n", "b.py": "gamma = 3\ndelta = 4\n"}
    dd = detect_duplicates(contents)
    assert dd.blocks == []


def test_plugins_empty_by_default(tmp_path):
    (tmp_path / "a.py").write_text("x=1\n", encoding="utf-8")
    res = scan(tmp_path)
    assert run_plugins(res) == {}


def test_cache_roundtrip_and_reuse(tmp_path):
    (tmp_path / "a.py").write_text("def f(x):\n    if x:\n        return 1\n    return 0\n", encoding="utf-8")
    first = scan(tmp_path, cache_data={})
    assert first.cache_entries  # populated after a fresh scan
    # Second scan seeded with the produced cache should yield identical stats.
    second = scan(tmp_path, cache_data=dict(first.cache_entries))
    assert [f.path for f in second.files] == [f.path for f in first.files]
    assert second.total_code == first.total_code
    assert {s.name for s in second.func_scores} == {s.name for s in first.func_scores}


def test_cache_entry_rebuild(tmp_path):
    (tmp_path / "a.py").write_text("def f():\n    return 1\n", encoding="utf-8")
    res = scan(tmp_path, cache_data={})
    rel, entry = next(iter(res.cache_entries.items()))
    stat, todos, scores, vendored = cachemod.rebuild(rel, entry)
    assert stat.path == rel
    assert vendored is False
