"""Detect vendored and generated files (linguist-style heuristics).

Vendored/generated files inflate line counts and pollute hotspots, so by default
they are counted separately and excluded from health/complexity. Pass
``--include-vendored`` to treat them as normal source.
"""
from __future__ import annotations

import re

# Path fragments that almost always indicate third-party or generated code.
_VENDOR_PATH = re.compile(
    r"(^|/)("
    r"vendor|vendored|third[_-]?party|node_modules|bower_components|"
    r"dist|build|out|target|\.min\.|"
    r"migrations|__generated__|generated|gen|"
    r"site-packages|eggs|\.egg-info|"
    r"jquery|bootstrap|modernizr"
    r")(/|\.|$)",
    re.IGNORECASE,
)

# Filename markers that can appear mid-name (searched anywhere in the path).
_VENDOR_SUFFIX = re.compile(
    r"("
    r"\.min\.(js|css)|"
    r"[._-]min\.|[._-]bundle\.|"
    r"_pb2\.|\.pb\.go|\.g\.dart|\.generated\.|\.designer\.cs|"
    r"package-lock\.json$|yarn\.lock$|pnpm-lock\.yaml$|poetry\.lock$|Cargo\.lock$"
    r")",
    re.IGNORECASE,
)

# Content markers emitted by common code generators.
_GENERATED_MARKERS = (
    "@generated",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "code generated by",
    "this file was automatically generated",
    "generated by protoc",
)


def is_vendored_path(rel_path: str) -> bool:
    return bool(_VENDOR_PATH.search(rel_path) or _VENDOR_SUFFIX.search(rel_path))


def is_generated_content(text: str) -> bool:
    """Check the first ~40 lines for a generator marker."""
    head = "\n".join(text.splitlines()[:40]).lower()
    return any(m in head for m in _GENERATED_MARKERS)


def is_vendored(rel_path: str, text: str) -> bool:
    return is_vendored_path(rel_path) or is_generated_content(text)
